export const creationsData = {
    id: 'creations',
    toplabel: 'our creations',
    btnlabel: 'see all',
    img1: require('../../image/image-deep-earth.jpg').default,
    alt1: 'deep earth',
    img2: require('../../image/image-night-arcade.jpg').default,
    alt2: 'night arcade',
    img3: require('../../image/image-soccer-team.jpg').default,
    alt3: 'soccer',
    img4: require('../../image/image-grid.jpg').default,
    alt4: 'grid',
    img5: require('../../image/image-from-above.jpg').default,
    alt5: 'above',
    img6: require('../../image/image-pocket-borealis.jpg').default,
    alt6: 'poccket',
    img7: require('../../image/image-curiosity.jpg').default,
    alt7: 'curiosity',
    img8: require('../../image/image-fisheye.jpg').default,
    alt8: 'fisheye',
}